**1. What makes NumPy.shape() different from NumPy.size()?**

In [2]:
import numpy as np
data= np.array([1,2,3,4,5,6,7,8,9,8,88])
np.size(data)   # np.size() Returns the size of the given axis(default 1) of the given array(or array-like) data. 
np.shape(data)  # np.shape() Returns the shape of the provided array or array like dataset. i.e. It returns a tuple with length of each exis of the given dataset as its members.


(11,)

**2. In NumPy, describe the idea of broadcasting.**
   <br>Answer: Broadcasting means the ability of numpy arrrays to indulge in arithmetic operation, even if their shapes are different
   1. If the arrays have different numbers of dimensions, the array with fewer dimensions is padded with ones on its leading (left) side.

   2. If the sizes of the corresponding dimensions are different, but one of them is equal to 1, then the array with size 1 is stretched or "broadcasted" to match the size of the other array along that dimension.

   3. If the sizes of the corresponding dimensions are different and neither of them is equal to 1, then the operation is not possible, and a "ValueError" is raised.

In [8]:
import numpy as np

a = np.array([1, 2, 3])     # shape: (3,)
b = np.array([[10], [20]])  # shape: (2, 1)


a+b

[[11 12 13]
 [21 22 23]]


array([[11, 12, 13],
       [21, 22, 23]])

In [10]:
a = np.array([1, 2, 3])     # shape: (3,)
b = np.array([10, 20])      # shape: (2,)
a+b
# This will show an error

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

**3. What makes Python better than other libraries for numerical computation?**

Answer.

If you meant `Numpy`: -> <br>
1. It has a huge ecosystem of developers. So support is easily available .
2. It is compatible with other major libraries like `pandas`, `statistics`, `scikit`.
3. It is heavily optimised and very flexible with features like `broadcasting`.


if you meant Python: -><br>        
1. It is the most popular language of 2023. 
2. It has a huge ecosystem, tus getting support will be extremely fast and easy.
3. It has highly optimised and specific numerical calculation libraries for every niche. like, `scikit`, `numpy`, `statistics`.
4. These libraries are heavily optimised too.


**4. How does NumPy deal with files?**

It uses various functions like
   - `numpy.loadtxt()`: This function reads data from a text file and returns an array. It is flexible and can handle different file formats, including CSV (Comma-Separated Values).
   - `numpy.genfromtxt()`: Similar to `loadtxt()`, this function reads data from text files, but it handles missing values and more complex data structures.
   - `numpy.fromfile()`: This function reads binary data from a file and returns an array.
    - `numpy.savetxt()`: This function saves an array to a text file, with options to specify the delimiter and formatting.
   - `numpy.ndarray.tofile()`: This method writes the array data to a file in binary format.
   - `numpy.save()`: This function saves an array to a binary file in NumPy's `.npy` format.

**5. Mention the importance of NumPy.empty().**

The `numpy.empty()` function is an important tool in NumPy as it creates a new array without initializing its elements to any specific values. Here are the key points highlighting the importance of `numpy.empty()`:

   1. Memory efficiency: The `numpy.empty()` function allocates memory for the array without initializing the elements. 

   2. Performance optimization: By avoiding the initialization of array elements, `numpy.empty()` allows for potential performance improvements. 
   3. Flexibility: `numpy.empty()` provides flexibility by allowing you to create arrays of a specific shape and data type. 
